# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='courseName',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
